### ISSUE TITLE
Mac issues with gramplet on Import

### ISSUE THREAD

**Issue by GaryGriffin** [jmichault/PersonFS#13]
Thanks for this interesting gramplet. I am using a Mac and ran in to an issue. I tried both the main and dev branches and both had this issue.

When I tried to import an individual or a tree, I get the error:

```
33434: ERROR: grampsapp.py: line 173: Unhandled exception
Traceback (most recent call last):
  File "/Users/gary/Desktop/Gramps 5.1.5.app/Contents/Resources/lib/python3.9/site-packages/gramps/gui/plug/_windows.py", line 807, in on_ok_clicked
    self.run() # activate results tab
  File "/Users/gary/Library/Application Support/gramps/gramps51/plugins/PersonFS-dev/Importo.py", line 863, in run
    importilo.importi(self,self.FS_ID)
  File "/Users/gary/Library/Application Support/gramps/gramps51/plugins/PersonFS-dev/Importo.py", line 562, in importi
    self.aldPersono(vokanto.dbstate.db, txn, fsPersono)
  File "/Users/gary/Library/Application Support/gramps/gramps51/plugins/PersonFS-dev/Importo.py", line 403, in aldPersono
    komparo.kompariFsGr(fsPersono,grPerson,db,None)
  File "/Users/gary/Library/Application Support/gramps/gramps51/plugins/PersonFS-dev/komparo.py", line 835, in kompariFsGr
    res = aldGepKomp(db, grPersono, fsPersono)
  File "/Users/gary/Library/Application Support/gramps/gramps51/plugins/PersonFS-dev/komparo.py", line 402, in aldGepKomp
    PersonFS.PersonFS.fs_Tree.add_persons(parents_ids)
AttributeError: 'NoneType' object has no attribute 'add_persons'
```

I resolved this by adding the following code to the aldGepKomp routine at the start up (where you are initializing things)

```
    if not PersonFS.PersonFS.fs_Tree:
      PersonFS.PersonFS.fs_Tree = tree.Tree()
      PersonFS.PersonFS.fs_Tree._getsources = False
```

With this change, the gramplet seemed to work correctly for Import. 

Thanks
Gary Griffin

**Comment by jmichault** [comment]
Can you test with releate 1.4.2 ?

**Comment by GaryGriffin** [comment]
I tried 1.4.2 but your dynamic use of pip is an issue. The gramps bundle includes python 3.9 whereas the system uses 3.8 . So running pip puts the files in the wrong location. 

I manually put requests in the correct location, but get the error on startup:
```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
2023-04-09 14:53:40.003: WARNING: _manager.py: line 307: Plugin error (from 'PersonFS'): cannot import name 'requests' from 'pip._vendor' (/Users/gary/Desktop/Gramps 5.1.5.app/Contents/Resources/lib/python3.9/site-packages/pip/_vendor/__init__.py)
```

**Comment by GaryGriffin** [comment]
To work around the gramps bundle, I put all of the pip-loaded packages into the same PersonFS folder. By overwriting the version number of gedcomx, I was able to run things. 

The original issue is fixed. Thanks

**Comment by GaryGriffin** [comment]
Tested on gramps 5.2 . Since it is distributed as a bundle, I manually uploaded the following packages to 

Gramps.app/Contents/Resources/lib/python3.11

the following packages (which are not in the bundle):

certifi-2024.2.2
idna-3.6
charset-normalizer-3.3.2
urllib3-2.2.1
gedcomx_v1-1.0.21
packaging-23.2
setuptools-69.1.1
requests-2.31.0

I also commented out the lines referencing pip in Importo.py and PersonFS.py
