### ISSUE TITLE
Import fails in Gramps 5.2

### ISSUE THREAD

**Issue by GaryGriffin** [jmichault/PersonFS#41]
Loaded modules in gramps 5.2 . 

When importing, it crashes with traceback:

 citation pas trouvée _FSFTID=QMY5-HHB
2024-03-02 11:35:30.312: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/Users/gary/Applications/Gramps5.2.app/Contents/Resources/lib/python3.11/site-packages/gramps/gui/plug/_windows.py", line 1813, in on_ok_clicked
    self.run()  # activate results tab
    ^^^^^^^^^^
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 1074, in run
    importilo.importi(self,self.FS_ID)
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 823, in importi
    self.aldPersono(vokanto.dbstate.db, txn, fsPersono)
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 631, in aldPersono
    c = aldFonto(db, txn, fsFonto.descriptionId,grPerson,grPerson.citation_list)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 429, in aldFonto
    linioj = sTitolo.split("\n")
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

Tried a different ID and crashed similar on location:

 citation pas trouvée _FSFTID=9KMN-N6P
2024-03-02 11:10:09.874: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/Users/gary/Applications/Gramps5.2.app/Contents/Resources/lib/python3.11/site-packages/gramps/gui/plug/_windows.py", line 1813, in on_ok_clicked
    self.run()  # activate results tab
    ^^^^^^^^^^
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 1074, in run
    importilo.importi(self,self.FS_ID)
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 823, in importi
    self.aldPersono(vokanto.dbstate.db, txn, fsPersono)
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 631, in aldPersono
    c = aldFonto(db, txn, fsFonto.descriptionId,grPerson,grPerson.citation_list)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary/Library/Application Support/gramps/gramps52/plugins/PersonFS/Importo.py", line 429, in aldFonto
    linioj = sTitolo.split("\n")
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by GaryGriffin** [comment]
I think if line 428 of Importo.py is changed to the below, it will work. At least it does not crash.

`if sTitolo and cTitolo and sourceDescription.resourceType == 'DEFAULT':`
